#!/bin/bash
rm -rf Makefile 
ln -s Makefile_beta10 Makefile

# reset GPUs in case they're in a bad state
echo 1 > /sys/kernel/debug/dri/0/i915_wedged
echo 0 > /sys/kernel/debug/dri/0/i915_error_state

source /data/oneapi_workshop/sc20/linux_prod/compiler/env/vars.sh

# advisor
source /data/oneapi_workshop/sc20/advisor_2021.1.1/advisor-vars.sh

export SYCL_BE=PI_LEVEL_ZERO
export LIBOMPTARGET_PLUGIN=LEVEL0
export ADVIXE_EXPERIMENTAL=gpu-profiling
export ADVIXE_MORE_GTPIN_OPTIONS="-ignore_l0_igc_info"



