#!/bin/bash
#module use /soft/restricted/CNDA/ccc_test/modulefiles/modulefiles-2021.10.30.001
#module add oneapi/2021.10.30.001
module add oneapi/release/2021.10.30.001
source /home/jkwack/gpfs_jkwack/Advisor_SDK_SC21/advisor_611353/advisor-vars.sh 

which icpx
which advisor

rm -rf Makefile
ln -s Makefile_2021.10.30.001 Makefile
